FROM ubuntu:trusty
MAINTAINER VENKY_DOCKER
RUN apt-get update
ADD https://pm.puppetlabs.com/puppet-agent/2017.1.1/1.9.3/repos/deb/yakkety/PC1/puppet-agent_1.9.3-1yakkety_amd64.deb /puppet-agent_1.9.3-1yakkety_amd64.deb 

CMD ["/bin/bash"]